//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DT2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dF5PDBafces79JW3AXo3o98dcn0v1jrfjNuN04h0eJ_eDA0zLZuSXey_cJ--FRjWonG5lHgxKaKriYxQS" +
            "WIF0A")]
        public string CloudStackSecretKey {
            get {
                return ((string)(this["CloudStackSecretKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("m4JGw31IgcvabsE9QwWqrHFukXK_LmYbaunFx2rApFcfZVoxJBNed0RgZ0suI3gksciAsoaAQXAB_zbTE" +
            "cRtXw")]
        public string CloudStackApiKey {
            get {
                return ((string)(this["CloudStackApiKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XenServer")]
        public string CloudStackHypervisor {
            get {
                return ((string)(this["CloudStackHypervisor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xdc1.DesktopWebApp.cambourne.cloud.com:80")]
        public string XenDesktopAdminAddress {
            get {
                return ((string)(this["XenDesktopAdminAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CloudPlatformHost")]
        public string XenDesktopHostingUnitName {
            get {
                return ((string)(this["XenDesktopHostingUnitName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DesktopWebApp.cambourne.cloud.com")]
        public string XenDesktopDomain {
            get {
                return ((string)(this["XenDesktopDomain"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xdc1.DesktopWebApp.cambourne.cloud.com")]
        public string XenDesktopDDC {
            get {
                return ((string)(this["XenDesktopDDC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Advanced-zone")]
        public string XenDesktopAvailabilityZone {
            get {
                return ((string)(this["XenDesktopAvailabilityZone"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c079a19f-7eb1-463c-b5bc-13d508584d5a")]
        public string CloudStackZoneId {
            get {
                return ((string)(this["CloudStackZoneId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TestDisableCatalogCreate {
            get {
                return ((bool)(this["TestDisableCatalogCreate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.50/Citrix/StoreWeb/")]
        public string XenDesktopStoreFrontUrl {
            get {
                return ((string)(this["XenDesktopStoreFrontUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pmlab.cpbm.citrite.net/portal/client/apis/CCPDIXON")]
        public string CloudStackUrl {
            get {
                return ((string)(this["CloudStackUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LDAP://CN=users,DC=DesktopWebApp,DC=cambourne,DC=cloud,DC=com")]
        public string LdapPath {
            get {
                return ((string)(this["LdapPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SecurityGroups {
            get {
                return ((string)(this["SecurityGroups"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\administrator.DesktopWebApp\\Documents\\GitHub\\DesktopWebApp\\DT2\\Utils")]
        public string PowerShellScriptsFolder {
            get {
                return ((string)(this["PowerShellScriptsFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckUserForCreatePrivileges {
            get {
                return ((bool)(this["CheckUserForCreatePrivileges"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("executable")]
        public string templatefilter {
            get {
                return ((string)(this["templatefilter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://pmlab.cpbm.citrite.net/portal/api")]
        public global::System.Uri CPBMEndPoint {
            get {
                return ((global::System.Uri)(this["CPBMEndPoint"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wNRXbfi96S3rLknkmG3t0qwGkQHX32RmQcAkvUVlAVGxetveDHXKYKoI5FZYlFfQ05k1QtbTgtAdc_F1e" +
            "7UDIw")]
        public string CPBMApiKey {
            get {
                return ((string)(this["CPBMApiKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6AYwvDsp9r6s-IgT4R9PUyynbb7h5Vo-3_hgwTTiBSHcO_lCOzrww_aUC-uhcEXEYGANvDjeGSwoqC6u5" +
            "GL_vA")]
        public string CPBMSecretKey {
            get {
                return ((string)(this["CPBMSecretKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TestDisableImageFetch {
            get {
                return ((bool)(this["TestDisableImageFetch"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IaaS US West")]
        public string CPBMServiceInstanceName {
            get {
                return ((string)(this["CPBMServiceInstanceName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TestDisableProductBundleGet {
            get {
                return ((bool)(this["TestDisableProductBundleGet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TestDisableServiceOfferingGet {
            get {
                return ((bool)(this["TestDisableServiceOfferingGet"]));
            }
        }
    }
}
